public static class Inspire
{
    public static class Image
    {
        public static readonly string[] Styles =
        {
            "Abstract Expressionism",
            "Airbrushing",
            "Anamorphosis",
            "Assemblage",
            "Baroque",
            "Bas-Relief",
            "Batik",
            "Block Printing",
            "Body Painting",
            "Calligraphy",
            "Ceramics",
            "Chiaroscuro",
            "Collage",
            "Cubism",
            "Cyanotype",
            "Dadaism",
            "Decollage",
            "Electrography",
            "Encaustic",
            "Engraving",
            "Fluxus",
            "Found Object Art",
            "Fresco-Secco",
            "Fresco",
            "Geometric Abstraction",
            "Glassblowing",
            "Gouache",
            "Graffiti",
            "Graffito",
            "Gyotaku",
            "Hyperrealism",
            "Impressionism",
            "Installation Art",
            "Kinbaku",
            "Kinetic Art",
            "Kinetic Sculpture",
            "Land Art",
            "Light Painting",
            "Mezzotint",
            "Minimalism",
            "Mixed Media",
            "Mosaic",
            "Neo-Dada",
            "Neo-Expressionism",
            "Op Art",
            "Photomontage",
            "Photorealism",
            "Pixel Art",
            "Plaster Casting",
            "Pointillism",
            "Primitivism",
            "Pyrography",
            "Quilling",
            "Repoussé",
            "Reverse Glass Painting",
            "Sand Art",
            "Scratchboard",
            "Shibori",
            "Stained Glass",
            "Stencil Art",
            "Street Art",
            "String Art",
            "Sumi-E",
            "Surrealism",
            "Surrealist Automatism",
            "Tachisme",
            "Tapestry",
            "Tilt-Shift Photography",
            "Trompe-L'œil",
            "Wire Sculpture",
            "Woodcut",
        };
        public static readonly string[] Artists =
        {
            "Ai Weiwei",
            "Alexander Calder",
            "Andy Warhol",
            "Anselm Kiefer",
            "Audrey Kawasaki",
            "Banksy",
            "Barbara Kruger",
            "Bridget Riley",
            "Cindy Sherman",
            "Dale Chihuly",
            "Damien Hirst",
            "David Hockney",
            "Egon Schiele",
            "Escher",
            "Fernando Botero",
            "Frank Stella",
            "Frida Kahlo",
            "Georgia O'keeffe",
            "Gerhard Richter",
            "Gustav Klimt",
            "H.R. Giger",
            "Henri Matisse",
            "Hieronymus Bosch",
            "Hokusai",
            "Jackson Pollock",
            "James Turrell",
            "Jean Dubuffet",
            "Jean-Michel Basquiat",
            "Jeff Koons",
            "Jenny Holzer",
            "Joan Miró",
            "Judy Chicago",
            "Kara Walker",
            "Käthe Kollwitz",
            "Katsushika Hokusai",
            "Kehinde Wiley",
            "Keith Haring",
            "Leonardo Da Vinci",
            "Leonora Carrington",
            "Louise Bourgeois",
            "Louise Nevelson",
            "Marina Abramović",
            "Mark Rothko",
            "Mark Ryden",
            "Mary Cassatt",
            "Maurizio Cattelan",
            "Nam June Paik",
            "Olafur Eliasson",
            "Pablo Picasso",
            "Remedios Varo",
            "René Magritte",
            "Roy Lichtenstein",
            "Salvador Dalí",
            "Shirin Neshat",
            "Takashi Murakami",
            "Vincent Van Gogh",
            "Wassily Kandinsky",
            "Yayoi Kusama",
            "Yinka Shonibare",
            "Yoko Ono",
            "Yves Klein",
            "Yves Tanguy",
            "Zdzisław Beksiński",
        };
        public static readonly string[] Materials =
        {
            "Acrylic Resin",
            "Airbrushing",
            "Ash",
            "Audience Participation",
            "Ballpoint Pen",
            "Basalt",
            "Beadwork",
            "Beeswax",
            "Bio-Art",
            "Biodegradable Plastics",
            "Birch Bark",
            "Blood",
            "Body Art",
            "Bookbinding Materials",
            "Botanical Materials",
            "Bubble Wrap",
            "Calligraphy Ink",
            "Casein Paint",
            "Cassette Tape",
            "Charcoal Pencils",
            "Charcoal",
            "Chocolate",
            "Choreography",
            "Clay",
            "Coffee Grounds",
            "Colored Pencils",
            "Computer Code",
            "Costume Design",
            "Cultural Artifacts",
            "Cyanotype Printing",
            "Digital 3d Printing",
            "Documentation Through Dance",
            "Documentation",
            "Egg Tempera Painting",
            "Eggshells",
            "Embroidery Floss",
            "Enamel",
            "Encaustic Painting",
            "Environmental Art",
            "Etching Press",
            "Fabric Scraps",
            "Food Items",
            "Fresco Painting",
            "Fresco Secco Painting",
            "Gesso",
            "Glassblowing",
            "Glitter",
            "Gouache Paint",
            "Graphite",
            "Gum Arabic",
            "Historical Artifacts",
            "Holographic Film",
            "Ice Casting",
            "Improvisation With Audience",
            "Improvisation",
            "Industrial Materials",
            "Ink Wash Painting",
            "Ink",
            "Inkjet Printing",
            "Installations Using Everyday Objects",
            "Interactive Installation",
            "Kinetic Sand",
            "Kinetic Sculpture",
            "Land Art",
            "Leather",
            "Light And Shadow Installation",
            "Light Graffiti",
            "Light Installation",
            "Light Painting",
            "Light Sculpture",
            "Light",
            "Lighting Design",
            "Macrame",
            "Man-Made Objects",
            "Manufactured Objects",
            "Medical Ephemera",
            "Metal Chasing",
            "Metal Scraps",
            "Natural Materials",
            "Natural Objects",
            "Natural Phenomena",
            "Natural Pigments",
            "Neon Light Sculpture",
            "Neon",
            "Objects",
            "Pastel Pencils",
            "Pencil",
            "Performance Art",
            "Plaster",
            "Plastic Objects",
            "Quilting Fabric",
            "Quilting",
            "Religious Iconography",
            "Resin Casting",
            "Rice Paper",
            "Rice",
            "Salt Dough",
            "Sand Art",
            "Sand",
            "Sandblasting",
            "Scratchboard Art",
            "Script Adaptation",
            "Script",
            "Sculpting With Natural Ice",
            "Sea Glass",
            "Set Design",
            "Silicone",
            "Soft Pastels",
            "Sound Design",
            "Sound Installation",
            "Spray Paint",
            "Stained Glass",
            "Stainless Steel",
            "Street Art Materials",
            "Street Art",
            "Tapestry Weaving",
            "Technological Objects",
            "Tempera Painting",
            "Textiles",
            "Thread",
            "Vegetable Dyes",
            "Video Art",
            "Watercolor Pencils",
            "Watercolor Sticks",
            "Watercolors",
            "Woodcut Printing",
            "Written Documents",
            "Yarn",
        };
        public static readonly string[] Places =
        {
            "Amazon Rainforest Canopy",
            "Amazon Rainforest Floor",
            "Amélie's Montmartre",
            "Ancient Roman Colosseum",
            "Antelope Canyon",
            "Astral Chain",
            "Astral Clocktower",
            "Aurora Borealis Over Snow-Capped Mountains",
            "Avatar's Pandora",
            "Bionic Commando Swinging Levels",
            "Blade Runner's Los Angeles",
            "Bolivian Salt Flats",
            "Brazil's Ventilation Ducts",
            "Brightly Colored Stalls",
            "Castlevania Boss Rooms",
            "Castlevania Clock Tower",
            "Castlevania",
            "Celestial Architecture, Majestic Scale And Power",
            "Chalk Cliffs",
            "Chasm Of Stars",
            "Cherry Blossom Festival In Japan",
            "City Of Tears",
            "Clock Town",
            "Cloud City Of Bespin",
            "Contra Jungle",
            "Contra Power-Up Capsules",
            "Coral Nursery",
            "Coral Reef After Bleaching",
            "Coral Reef Teeming With Life",
            "Death Star Trench Run",
            "Donkey Kong Jungle",
            "Double Dragon Neon Signs",
            "Dr. Seuss's 'Lorax' Truffula Forest",
            "Dream World",
            "Dreaming City",
            "Dreaming",
            "Dreamlike Landscapes, Shifting Realities",
            "Drowned City",
            "Dunes Of Time",
            "Dunes",
            "Easter Island At Dawn",
            "Easter Island",
            "Egyptian Pyramids At Sunset",
            "Elysian Fields",
            "Elysium",
            "Endless Pampas Grasslands Of Argentina",
            "Endless Red Sand Dunes At Sunset",
            "Endless Sand Dunes Of The Sahara",
            "Endless Steppes Of Mongolia",
            "Endless Tea Plantations In China",
            "Endless Tundra Landscape In Winter",
            "Endless White Sand Beaches Of The Maldives",
            "Escher's Staircase Illusion",
            "Eternal Sunshine Of The Spotless Mind's Lacuna",
            "Excitebike Tracks",
            "Fifth Element's Fhloston Paradise",
            "Final Fantasy Cloud Of Darkness",
            "Forbidden Grove",
            "Galaga Bosses",
            "Gaudi's Sagrada Familia",
            "Geothermal Geysers In Iceland",
            "Glade",
            "Glowing Jellyfish Bloom In The Deep Ocean",
            "Glowing Mushroom Forest At Night",
            "Glowing Mushrooms In A Forest",
            "Gradius Backgrounds",
            "Grand Bazaar",
            "Grand Budapest Hotel's Funicular Railway",
            "Grand Budapest Hotel",
            "Grand Prismatic Spring Aerial View",
            "Grand Prismatic Spring",
            "Green Hill Zone",
            "Hanging Gardens Of Babylon",
            "Hidden Forest",
            "Hobbit Holes Of The Shire",
            "Hyrule Field",
            "Hyrule Overworld",
            "Ice Climbers Mountain",
            "Icelandic Geysers Erupting",
            "Icelandic Glaciers",
            "Icelandic Moss Fields",
            "Icy Landscape",
            "Inception's Dream City",
            "Inkwell Isles",
            "Interior Of A Gothic Cathedral",
            "Interior Of A Spaceship",
            "Isle Of The Dead",
            "Japanese Bamboo Forest",
            "Jordan",
            "Kamino",
            "Kelp Forest",
            "Kill Bill's Tokyo Alleyway",
            "Labyrinthine Corridors, Jellyfish Enemies",
            "Lavender Fields After Rain",
            "Lavender Fields At Sunrise",
            "Lavender Fields During A Thunderstorm",
            "Link's Awakening Koholint Island",
            "Lush Amazon Rainforest Canopy",
            "Lush Rice Terraces With Farmers Working",
            "M.C. Escher's Lithograph 'Hand With Reflecting Sphere'",
            "Mad Max: Fury Road's Wasteland",
            "Magritte's 'The Son Of Man' Painting",
            "Martian Canyons",
            "Martian Landscape",
            "Masai Mara During Migration",
            "Matrix",
            "Maw",
            "Mega Man Stages",
            "Mega Man Wily's Castle",
            "Metro",
            "Metroid Brinstar Caves",
            "Milky Way Galaxy",
            "Miyazaki's Spirited Away Bathhouse",
            "Mojave Wasteland",
            "Monet's Haystack Series",
            "Monet's Water Lilies Close-Up",
            "Monet's Water Lily Pond",
            "Moon",
            "Mushroom Kingdom",
            "Neon Dubai Cityscape",
            "Neon Las Vegas During The Day",
            "Neon Las Vegas From Space",
            "Neon Las Vegas Strip",
            "Neon Signs Of Hong Kong At Night",
            "Neon Tokyo Alleyway",
            "Neon Tokyo At Night From A Bullet Train Window",
            "Neon Tokyo During A Power Outage",
            "Neon Tokyo Streetscape",
            "Neon Tokyo Viewed From A Rooftop",
            "Neon-Lit Cityscape Reflected In A Rainy Street",
            "Nibel",
            "Night City",
            "Ninja Gaiden Rooftops",
            "Organic Tunnels, Morphing Enemies",
            "Pac-Man Maze",
            "Pan's Labyrinth's Labyrinth",
            "Pandora",
            "Petra,",
            "Punch-Out!! Ring",
            "Punch-Out!! Victory Fanfare",
            "R-Type Force Fields",
            "Rainbow Road",
            "Rapture Central Bathysphere",
            "Rapture",
            "Rice Paddies During Harvest",
            "Royal Tenenbaums' House",
            "Ruins",
            "Salt Flats At Sunset",
            "Salvador Dalí's Melting Clocks",
            "Scottish Highlands",
            "Shining's Overlook Hotel",
            "Shipwreck Encrusted With Barnacles",
            "Shipwreck",
            "Shire",
            "Shivering Isles",
            "Side-Scrolling Streets",
            "Silent Hill",
            "Skyforge",
            "Skyloft",
            "Spirited Away's Bathhouse",
            "Starry Sky Over The Atacama Desert",
            "Tetris Playing Field",
            "The Great Barrier Reef Aerial View",
            "The Great Salt Lake",
            "The Milky Way Galaxy Core",
            "Tibetan Prayer Flags Fluttering In The Wind",
            "Troll Markets Of Scandinavian Folklore",
            "Tulip Fields",
            "Uldum",
            "Underdark",
            "Upside Down",
            "Van Gogh's Starry Night Sky",
            "Van Gogh's Wheat Field Under A Crows' Sky",
            "Venetian Canals At Dusk",
            "Vines And Spores",
            "Volcanic Eruption",
            "Wakanda",
            "Warp Pipes",
            "Warp",
            "Whiterun",
        };
    }

    public static class Sound
    {
        public static readonly string[] Styles =
        {
           "Acid House",
           "Afro-Cuban Jazz",
           "Afrobeat",
           "Appalachian Folk",
           "Avant-Garde Jazz",
           "Balinese Gamelan",
           "Balkan Brass",
           "Barbershop Harmony",
           "Barbershop Quartet",
           "Baroque Fugue",
           "Bhangra",
           "Bluegrass",
           "Bollywood Music",
           "Bollywood",
           "Bossa Nova",
           "Brazilian Samba",
           "Butoh Music",
           "Cajun Music",
           "Cajun Zydeco",
           "Carnatic Music",
           "Celtic Punk",
           "Chiptune",
           "Delta Blues",
           "Drone Music",
           "Drone",
           "Drum And Bass",
           "Electroswing",
           "Flamenco",
           "Gagaku",
           "Gagok",
           "Gamelan",
           "Gospel",
           "Gregorian Chant",
           "Gypsy Jazz",
           "Hindustani Classical",
           "Industrial",
           "J-Pop",
           "Jarocho",
           "Javanese Gamelan",
           "Jig",
           "Jive",
           "K-Pop",
           "Klezmer",
           "Mbira Music",
           "Mongolian Throat Singing",
           "Neoclassical",
           "Norteño",
           "Post-Rock",
           "Progressive Metal",
           "Raï",
           "Reggae Dub",
           "Reggaeton",
           "Shanty",
           "Shoegaze",
           "Sitar Music",
           "Ska",
           "Slavic Polyphony",
           "Synthwave",
           "Tuvan Khoomei",
           "Tuvan Throat Singing",
           "Zydeco",
        };
        public static readonly string[] Ambiances =
        {
            "Animal Call",
            "Apples Crunching",
            "Ball Bouncing",
            "Birdsong",
            "Blacksmith Hammering Metal",
            "Blades Of A Helicopter Whirring",
            "Book Slamming Shut",
            "Camera Shutter Click",
            "Camera Shutter Rapidly Clicking",
            "Cat Purring",
            "Chains Clanking",
            "Chainsaw Revving",
            "Chalk Screech On Blackboard",
            "City Ambience",
            "Clock Ticking",
            "Coffee Machine Brewing",
            "Coins Cascading",
            "Coins Clinking",
            "Coins Dropping",
            "Coins Rolling",
            "Crackling Fire",
            "Crackling Vinyl",
            "Crickets Chirping",
            "Crowd Cheering",
            "Cutting Fabric",
            "Dog Barking",
            "Door Creaking",
            "Doorbell Chime",
            "Factory Machinery",
            "Fireworks Exploding",
            "Footsteps On Creaky Stairs",
            "Footsteps On Gravel",
            "Fork Scraping Plate",
            "Glass Clinking",
            "Glowing Embers Crackling",
            "Gong Resonance",
            "Gurgling Water",
            "Heartbeat",
            "Hot Air Balloon Burner Roaring",
            "Insects Buzzing",
            "Keyboard Clicks",
            "Laughter Box",
            "Laughter",
            "Ocean Waves",
            "Pages Flipping Rapidly In A Book",
            "Pages Fluttering",
            "Pages Turning",
            "Pen Scratching Rapidly On Paper",
            "Pen Scratching",
            "Pencil Tapping",
            "Popcorn Kernels Popping",
            "Rain Hammering On A Metal Roof",
            "Rain Splattering On Leaves",
            "Raindrops On Leaves",
            "Rice Crackling",
            "Rocks Tumbling Down A Mountainside",
            "Rustling Leaves",
            "Rusty Lock Creaking Open",
            "Rusty Swing Creaking Back And Forth",
            "Sawing Wood",
            "Scuba Diver Breathing",
            "Short Circuit Crackle",
            "Sizzling Bacon",
            "Soldering Iron Hiss",
            "Sputtering Campfire Embers",
            "Sputtering Engine",
            "Teletype Machine Clattering",
            "Thunderclap",
            "Train Wheels Screeching",
            "Train Whistle",
            "Typing On A Typewriter",
            "Water Dripping",
            "Whales Singing",
            "Whistleblower",
            "Wind Chimes",
            "Wind Howling",
            "Wind Rushing Through A Tunnel",
            "Wind Whistling Through A Crack In The Wall",
            "Wind Whistling Through A Keyhole",
            "Wind Whistling Through Trees",
        };
        public static readonly string[] Composers =
        {
            "Aaron Copland",
            "Alice Coltrane",
            "Antonio Carlos Jobim",
            "Antonio Vivaldi",
            "Aram Khachaturian",
            "Aretha Franklin",
            "Arvo Pärt",
            "Astor Piazzolla",
            "Béla Bartók",
            "Billie Holiday",
            "Bob Dylan",
            "Brian Eno",
            "Carlos Santana",
            "Clara Schumann",
            "Claude Debussy",
            "Dmitri Shostakovich",
            "Duke Ellington",
            "Edvard Grieg",
            "Ennio Morricone",
            "Eric Whitacre",
            "Erik Satie",
            "Franz Liszt",
            "Franz Schubert",
            "Giacomo Puccini",
            "Giuseppe Verdi",
            "Gustav Mahler",
            "Hector Berlioz",
            "Henryk Górecki",
            "Hildegard Von Bingen",
            "Igor Stravinsky",
            "Jean Sibelius",
            "Johann Sebastian Bach",
            "Johann Strauss Ii",
            "John Cage",
            "John Coltrane",
            "John Philip Sousa",
            "John Williams",
            "Ludwig Van Beethoven",
            "Meredith Monk",
            "Olivier Messiaen",
            "Philip Glass",
            "Pyotr Ilyich Tchaikovsky",
            "Richard Wagner",
            "Scott Joplin",
            "Sergei Prokofiev",
            "Sergei Rachmaninoff",
            "Steve Reich",
            "Sun Ra",
            "Toru Takemitsu",
            "Wolfgang Amadeus Mozart",
        };
        public static readonly string[] Instruments =
        {
            "Accordion",
            "Alphorn",
            "Anklung",
            "Autoharp",
            "Bagpipes",
            "Balafon",
            "Balalaika",
            "Banjo",
            "Bansuri",
            "Berimbau",
            "Bodhrán",
            "Bouzouki",
            "Cajon",
            "Cajón",
            "Castanets",
            "Cello",
            "Chapman Stick",
            "Chimes",
            "Clarinet",
            "Claves",
            "Clavichord",
            "Clavinet",
            "Crumhorn",
            "Daf",
            "Dan Moi",
            "Dhol",
            "Didgeridoo",
            "Digeridoo",
            "Dizi",
            "Djembe",
            "Drum Machine",
            "Drum Set",
            "Electric Guitar",
            "Erhu",
            "Flute",
            "Glockenspiel",
            "Gong",
            "Guitar",
            "Guzheng",
            "Hammered Dulcimer",
            "Handpan",
            "Hang Drum",
            "Harmonica",
            "Harmonium",
            "Harp",
            "Harpsichord",
            "Huqin",
            "Hurdy-Gurdy",
            "Jaw Harp",
            "Kalimba",
            "Kazoo",
            "Keyboard",
            "Koto",
            "Lute",
            "Marimba",
            "Mbira",
            "Melodica",
            "Morin Khuur",
            "Music Box",
            "Music Stand",
            "Oboe",
            "Ocarina",
            "Ondes Martenot",
            "Oud",
            "Piano",
            "Pipa",
            "Recorder",
            "Sanshin",
            "Santoor",
            "Saxophone",
            "Sequencer",
            "Shakuhachi",
            "Shamisen",
            "Shepard's Flute",
            "Singing Bowl",
            "Sitar",
            "Sousaphone",
            "Steel Pan",
            "Steel Tongue Drum",
            "Tabla",
            "Taiko Drum",
            "Taishogoto",
            "Tambourine",
            "Tambura",
            "Theremin",
            "Triangle",
            "Trumpet",
            "Ukulele",
            "Vibraphone",
            "Violin",
            "Xylophone",
        };
    }

    public static class Color
    {
        public static readonly string[] Red =
        {
            "Amber",
            "Amour",
            "Apricot",
            "Ardent",
            "Ardor",
            "Aurora",
            "Autumn",
            "Ballet",
            "Bittersweet",
            "Blaze",
            "Blithe",
            "Blossom",
            "Blush",
            "Boudoir",
            "Bubble",
            "Bubblegum",
            "Burgundy",
            "Caramel",
            "Cardinal",
            "Carmine",
            "Carnal",
            "Cerise",
            "Cherries",
            "Cherub",
            "Cinnabar",
            "Citrine",
            "Citrus",
            "Claret",
            "Cochineal",
            "Copper",
            "Coquelicot",
            "Coral",
            "Coruscate",
            "Cotton Candy",
            "Cotton",
            "Crimson",
            "Cupcake",
            "Cupid",
            "Danger",
            "Delicate",
            "Ember",
            "Embers",
            "Empyrean",
            "Enchantment",
            "Enigma",
            "Enticement",
            "Envy",
            "Ephemeral",
            "Eros",
            "Ethereal",
            "Euphoria",
            "Fiesta",
            "Firelight",
            "Flamboyant",
            "Flamenco",
            "Flamingo",
            "Flare",
            "Fluff",
            "Fuchsia",
            "Garnet",
            "Glow",
            "Goldfish",
            "Grace",
            "Harvest",
            "Heartache",
            "Incandescent",
            "Incendiary",
            "Inferno",
            "Innocence",
            "Juicy",
            "Lollipop",
            "Lurid",
            "Lust",
            "Luxuriant",
            "Magenta",
            "Magma",
            "Maracas",
            "Maraschino",
            "Marigold",
            "Maroon",
            "Marshmallow",
            "Masquerade",
            "Melancholy",
            "Melody",
            "Merlot",
            "Nebula",
            "Opal",
            "Papaya",
            "Paprika",
            "Paradise",
            "Passion",
            "Peony",
            "Persimmon",
            "Petal",
            "Phoenix",
            "Pomegranate",
            "Pulsar",
            "Pumpkin",
            "Quasar",
            "Quiver",
            "Radiance",
            "Rebellion",
            "Reverie",
            "Revolution",
            "Rhapsody",
            "Rosé",
            "Rosewater",
            "Rouge",
            "Rubicund",
            "Ruby",
            "Rust",
            "Saffron",
            "Sakura",
            "Sangria",
            "Sanguinity",
            "Scarlet",
            "Seashell",
            "Serenade",
            "Serenity",
            "Shroud",
            "Sizzle",
            "Sovereignty",
            "Spice",
            "Strawberry",
            "Sublime",
            "Sunrise",
            "Sunset",
            "Surreptitious",
            "Sweetheart",
            "Tang",
            "Tangelo",
            "Tangerine",
            "Tangy",
            "Temerity",
            "Tempest",
            "Temptation",
            "Temptress",
            "Tenderness",
            "Terracotta",
            "Tiger",
            "Tryst",
            "Vermilion",
            "Vermillion",
            "Vibrant",
            "Vitality",
            "Vivacious",
            "Whimsical",
            "Whimsy",
            "Whisper",
            "Zest",
            "Zesty",
        };
        public static readonly string[] Yellow =
        {
            "Acrimony",
            "Alchemy",
            "Alertness",
            "Amber",
            "Ancient Chinese Palace",
            "Ancient Egyptian Tomb",
            "Antique Book Binding",
            "Antique Map",
            "Antiquity",
            "Apathy And Lethargy",
            "Apathy",
            "Apricot",
            "Audacity",
            "Autumn Leaves",
            "Bakelite",
            "Banana Laffy Taffy",
            "Banana Peel",
            "Banana Plantation",
            "Bark",
            "Beehive",
            "Bifurcation",
            "Birch Bark Canoe",
            "Bronze",
            "Bumblebee",
            "Buttercup Meadow",
            "Buttercup",
            "Buttercups",
            "Butterflies",
            "Buzz",
            "Calmness",
            "Canary Islands",
            "Canary",
            "Caution Tape",
            "Caution",
            "Celebration And Festivities",
            "Celebration",
            "Champagne",
            "Chartreuse",
            "Cheese Market",
            "Cheese",
            "Chessboard",
            "Chestnut",
            "Chicks",
            "Childhood Innocence",
            "Childhood",
            "Chocolate Chip Cookie",
            "Cinnamon",
            "Citrine",
            "Citrus",
            "Cocoa",
            "Coffee Grounds",
            "Construction Crane",
            "Construction Zone",
            "Contentment",
            "Corn On The Cob",
            "Cowardice And Timidity",
            "Cowardice",
            "Crackle",
            "Cream Cheese",
            "Cream",
            "Creativity",
            "Curiosity",
            "Currency",
            "Daffodil",
            "Daffodils",
            "Dandelion",
            "Dawn",
            "Decadence",
            "Deception",
            "Departure",
            "Desert Landscape",
            "Disdain",
            "Disintegration And Decay",
            "Disintegration",
            "Disorientation",
            "Disquiet",
            "Dissonance And Clashing Ideas",
            "Dissonance",
            "Electrode",
            "Envy And Jealousy",
            "Envy",
            "Espresso Machine",
            "Espresso",
            "Euphoria",
            "Excitement",
            "Exploration And Uncharted Territory",
            "Exploration",
            "Fakeness",
            "Fertile",
            "Fever",
            "Flamenco Dancer's Dress",
            "Fortitude",
            "Fragile",
            "Fragility And Vulnerability",
            "Fragility",
            "Freckles",
            "Furtive",
            "Gilt",
            "Gold Medal",
            "Gold Mine",
            "Gold",
            "Goldfish Cracker",
            "Goldfish",
            "Goldilocks",
            "Highlighter",
            "Honey Gold",
            "Honey",
            "Honeycomb",
            "Humility And Modesty",
            "Humility",
            "Ideas",
            "Illumination And Revelation",
            "Illumination",
            "Immaturity",
            "Impermanence",
            "Innovation And Progress",
            "Innovation",
            "Intellectual Stimulation",
            "Ivory",
            "Jacket",
            "Jealousy",
            "Joy",
            "Khaki",
            "Kindergarten Classroom",
            "Laughter",
            "Laurel",
            "Leather",
            "Lemon Chiffon",
            "Lemon Orchard",
            "Lemon",
            "Lemons",
            "Levity",
            "Lightheartedness",
            "Loneliness",
            "Luxury And Opulence",
            "Mahogany",
            "Maize",
            "Marigold",
            "Maturity And Wisdom",
            "Maturity",
            "Mellowness",
            "Mental Clarity And Focus",
            "Midas Touch",
            "Mimosa",
            "Mole",
            "Moonlight",
            "Mustard Factory",
            "Mustard",
            "Neon Sign District",
            "New Beginnings",
            "Nickel",
            "Nostalgia And Faded Memories",
            "Nostalgia",
            "Ochre",
            "Olympic Podium",
            "Optimism",
            "Opulence",
            "Pages",
            "Path",
            "Peace",
            "Pencils",
            "Perch",
            "Persistence",
            "Pineapple",
            "Playfulness And Lightheartedness",
            "Playfulness",
            "Post-It Note",
            "Rebellion And Defiance",
            "Rebellion",
            "Renewal",
            "Revelation",
            "Royalty",
            "Rubber Band",
            "Rubber Ducky",
            "Rust",
            "Saddle",
            "Saffron",
            "Scaffolding",
            "School Bus",
            "School Cafeteria",
            "Sepia",
            "Serenity",
            "Soil",
            "Spark",
            "Stagnation And Lack Of Growth",
            "Stagnation",
            "Static Shock",
            "Static",
            "Summersaults",
            "Summertime And Warmth",
            "Sunflower Field",
            "Sunflower Seed",
            "Sunflowers",
            "Taxi Light",
            "Taxi Stand",
            "Taxi",
            "Tennis Court",
            "Terracotta",
            "Tesla Coil",
            "Thunderclap",
            "Topaz",
            "Tour De France",
            "Transience And Impermanence",
            "Transience",
            "Treachery And Deceit",
            "Treachery",
            "Treasure",
            "Trophy",
            "Truffle",
            "Twig",
            "Vanilla",
            "Vineyards",
            "Vulnerability",
            "Walnut",
            "Warmth",
            "Warning",
            "Whisper",
            "Wilderness",
            "Yolk",
            "Zeus",
            "Zinc",
        };
        public static readonly string[] Green =
        {
            "Absinthe",
            "Abundance And Fertility",
            "Adventure",
            "Alien And Extraterrestrial",
            "Ambivalence",
            "Apathy",
            "Apple",
            "Artichoke",
            "Asparagus",
            "Awning",
            "Backstage And Preparation",
            "Balance And Harmony",
            "Balance",
            "Bean",
            "Beret",
            "Billiard Ball",
            "Bowling Alley",
            "Broccoli Floret",
            "Button",
            "Cactus Flower",
            "Cactus Garden",
            "Cactus",
            "Card",
            "Caterpillar",
            "Caution",
            "Chartreuse",
            "Chessboard",
            "Chile Cheeseburger Stand",
            "Chili Pepper",
            "Chlorophyll",
            "Christmas Tree",
            "Circuit Board",
            "Clover",
            "Complacency",
            "Decay And Putrefaction",
            "Deception And Trickery",
            "Disgust",
            "Disquiet",
            "Dollar Bill",
            "Dragonfly Wings",
            "Eco-Friendliness",
            "Ecto-1",
            "Emerald Cut",
            "Emerald Mine",
            "Emerald Tablet",
            "Emerald",
            "Environmentalism",
            "Envy Adams' Emerald City",
            "Envy And Jealousy",
            "Envy",
            "Eucalyptus",
            "Evergreen",
            "Fingerprint",
            "Firework Burst",
            "Fixation",
            "Folklore And Mythology",
            "Forbidden Knowledge And Mystery",
            "Forest",
            "Fortune",
            "Fresh Starts",
            "Frog",
            "Gangrene",
            "Gecko",
            "Gemstone Cluster",
            "Genetically Modified Food Aisle",
            "Go-Ahead",
            "Granny Smith Apple",
            "Grasshopper",
            "Greenback",
            "Greenhorn",
            "Growth And Prosperity",
            "Growth Mindset",
            "Growth",
            "Guacamole",
            "Hope",
            "Inexperience",
            "Insecurity",
            "Jade Market",
            "Jade",
            "Jealousy",
            "Kermit Green",
            "Kermit The Frog",
            "Kermit",
            "Keyhole",
            "Khaki",
            "Kiwi Fruit",
            "Kiwi",
            "Kryptonite",
            "Ladybug",
            "Leaf",
            "Lily Pad",
            "Lime",
            "Lizard",
            "Luck",
            "Malachite",
            "Mango",
            "Marble Quarry",
            "Marble",
            "Matcha",
            "Metamorphosis",
            "Miniature Golf Course",
            "Mint",
            "Moss Patch",
            "Moss-Covered Ancient Ruins",
            "Moss",
            "Naiveté",
            "National Identity",
            "Nausea",
            "Nickelodeon Studios",
            "Northern Lights",
            "Nostalgia",
            "Obsession",
            "Olive Drab",
            "Olive Oil",
            "Olive",
            "Onion",
            "Operating Room",
            "Opulence",
            "Paddy Field",
            "Peace",
            "Peridot",
            "Permission",
            "Pickle",
            "Pine Tree",
            "Pistachio",
            "Playing Card",
            "Playing Die",
            "Poison",
            "Pool Table",
            "Possessiveness",
            "Power Button",
            "Praying Mantis",
            "Rainforest Canopy",
            "Rainforest",
            "Recycling Center",
            "Refreshment",
            "Regeneration",
            "Relief",
            "Renewal",
            "Reptile",
            "Room",
            "Scottish Highlands",
            "Scottish Tartan",
            "Seafoam",
            "Second Chances",
            "Security",
            "Shamrock Shake Stand",
            "Shamrock",
            "Slime Splat",
            "Snake",
            "Stagnation",
            "Sustainability",
            "Tadpole",
            "Tea Bag",
            "Tea Plantation",
            "Tea",
            "Technological Innovation",
            "Tetris Z Block",
            "Thumb",
            "Toxicity",
            "Traffic Light",
            "Tranquility",
            "Transformation",
            "Trust",
            "Unexplored Territory",
            "Verdant",
            "Verdigris-Coated Copper Roof",
            "Verdigris",
            "Verdure",
            "Vine",
            "Vineyard",
            "Viridescent",
            "Wealth",
        };
        public static readonly string[] White =
        {
            "Achromatopsia",
            "Alba",
            "Albino Animal",
            "Albino",
            "Angel Falls",
            "Angel Halo",
            "Anticipation",
            "Apochromatism",
            "Aseptic Operating Room",
            "Awe",
            "Baihu",
            "Beach",
            "Belyni",
            "Blancmange Mold",
            "Blank Page",
            "Blindness",
            "Blizzard",
            "Blood Cell",
            "Bone",
            "Boredom",
            "Buffalo Calf Woman",
            "Canvas",
            "Cave Formation",
            "Chalk Cliffs",
            "Chalk Mine",
            "Chalk",
            "Chastity",
            "Check",
            "Chocolate Chip",
            "Clarity",
            "Cleanliness",
            "Cloud Forest",
            "Cloud",
            "Cold",
            "Coldness",
            "Condition",
            "Confusion",
            "Crescent Moon",
            "Desert",
            "Diamond",
            "Dome",
            "Dove",
            "Dwarf",
            "Elephant",
            "Emptiness",
            "Flag",
            "Fragile",
            "Fragility",
            "Ghost",
            "Glacier Surface",
            "Glare",
            "Gold",
            "Grotto",
            "Guan Yin",
            "Hathor",
            "Hippolyta",
            "Hole Accretion Disk",
            "Hole",
            "Hope",
            "Hotel",
            "House Lawn",
            "House",
            "Ice Rink",
            "Inanna",
            "Innocence",
            "Isle Of Skye",
            "Isolation",
            "Ix Chel",
            "Kayaking",
            "Knight",
            "Leukothea",
            "Lie",
            "Light Bulb",
            "Loneliness",
            "Mami Wata",
            "Marble Quarry",
            "Marker",
            "Melancholy",
            "Menes",
            "Milk",
            "Minimalism",
            "Mourning",
            "New Beginning",
            "New Beginnings",
            "Noise Generator",
            "Noise Graph",
            "Noise Machine",
            "Noise Sleep App",
            "Noise Waveform",
            "Noise",
            "Numbness",
            "Oshun",
            "Pagoda",
            "Pass And Yukon Route",
            "Peace",
            "Pele",
            "Pepper",
            "Placeholder",
            "Pocket",
            "Polar Bear Habitat",
            "Porcelain Factory Workshop",
            "Porcelain Factory",
            "Porcelain",
            "Purity",
            "Quan Yin Pusa",
            "Rapids",
            "Renewal",
            "Rice Grain",
            "Rice Paddy Field",
            "Rice Paddy",
            "Room Art Installation",
            "Room",
            "Sachal Saraswati",
            "Salt Flats",
            "Sand Beach",
            "Sea",
            "Secrecy",
            "Selene",
            "Serenity",
            "Silence",
            "Simplicity",
            "Skadi",
            "Ski Slope",
            "Ski Slopes",
            "Snowblindness",
            "Snowdrift",
            "Snowfall",
            "Snowflake",
            "Snowy Mountain Peak",
            "Space",
            "Sterile",
            "Sterility",
            "Surprise",
            "Surrender",
            "Tabula Rasa",
            "Tank Mountain Regional Park",
            "Tara",
            "Tennis Ball",
            "Tower Of Thessaloniki",
            "Truffle",
            "Ushas",
            "Vanilla",
            "Verse",
            "Vulnerability",
            "Water Rafting",
            "Wedding",
            "White-Out ",
            "Whiteboard",
            "Whitecaps",
            "Whitechapel District",
            "Whitewash",
            "Whitewater",
            "Winter Wonderland",
            "Xochipilli",
            "Yue Lao",
            "Yuki-Onna",
            "Zahao",
            "Zebra Stripes",
            "Zebra",
            "Zhi Nu",
            "Zorya Utrennyaya",
        };
    }
}