public static class Inspire
{
    public static readonly string[] Image =
    {
        "Abstract Expressionism",
        "Acrylic Resin",
        "Ai Weiwei",
        "Airbrushing",
        "Alexander Calder",
        "Amazon Rainforest Canopy",
        "Amazon Rainforest Floor",
        "Amélie's Montmartre",
        "Anamorphosis",
        "Ancient Roman Colosseum",
        "Andy Warhol",
        "Anselm Kiefer",
        "Antelope Canyon",
        "Ash",
        "Assemblage",
        "Astral Chain",
        "Astral Clocktower",
        "Audience Participation",
        "Audrey Kawasaki",
        "Aurora Borealis Over Snow-Capped Mountains",
        "Avatar's Pandora",
        "Ballpoint Pen",
        "Banksy",
        "Barbara Kruger",
        "Baroque",
        "Bas-Relief",
        "Basalt",
        "Batik",
        "Beadwork",
        "Beeswax",
        "Bio-Art",
        "Biodegradable Plastics",
        "Bionic Commando Swinging Levels",
        "Birch Bark",
        "Blade Runner's Los Angeles",
        "Block Printing",
        "Blood",
        "Body Art",
        "Body Painting",
        "Bolivian Salt Flats",
        "Bookbinding Materials",
        "Botanical Materials",
        "Brazil's Ventilation Ducts",
        "Bridget Riley",
        "Brightly Colored Stalls",
        "Bubble Wrap",
        "Calligraphy Ink",
        "Calligraphy",
        "Casein Paint",
        "Cassette Tape",
        "Castlevania Boss Rooms",
        "Castlevania Clock Tower",
        "Castlevania",
        "Celestial Architecture, Majestic Scale And Power",
        "Ceramics",
        "Chalk Cliffs",
        "Charcoal Pencils",
        "Charcoal",
        "Chasm Of Stars",
        "Cherry Blossom Festival In Japan",
        "Chiaroscuro",
        "Chocolate",
        "Choreography",
        "Cindy Sherman",
        "City Of Tears",
        "Clay",
        "Clock Town",
        "Cloud City Of Bespin",
        "Coffee Grounds",
        "Collage",
        "Colored Pencils",
        "Computer Code",
        "Contra Jungle",
        "Contra Power-Up Capsules",
        "Coral Nursery",
        "Coral Reef After Bleaching",
        "Coral Reef Teeming With Life",
        "Costume Design",
        "Cubism",
        "Cultural Artifacts",
        "Cyanotype Printing",
        "Cyanotype",
        "Dadaism",
        "Dale Chihuly",
        "Damien Hirst",
        "David Hockney",
        "Death Star Trench Run",
        "Decollage",
        "Digital 3d Printing",
        "Documentation Through Dance",
        "Documentation",
        "Donkey Kong Jungle",
        "Double Dragon Neon Signs",
        "Dr. Seuss's 'Lorax' Truffula Forest",
        "Dream World",
        "Dreaming City",
        "Dreaming",
        "Dreamlike Landscapes, Shifting Realities",
        "Drowned City",
        "Dunes Of Time",
        "Dunes",
        "Easter Island At Dawn",
        "Easter Island",
        "Egg Tempera Painting",
        "Eggshells",
        "Egon Schiele",
        "Egyptian Pyramids At Sunset",
        "Electrography",
        "Elysian Fields",
        "Elysium",
        "Embroidery Floss",
        "Enamel",
        "Encaustic Painting",
        "Encaustic",
        "Endless Pampas Grasslands Of Argentina",
        "Endless Red Sand Dunes At Sunset",
        "Endless Sand Dunes Of The Sahara",
        "Endless Steppes Of Mongolia",
        "Endless Tea Plantations In China",
        "Endless Tundra Landscape In Winter",
        "Endless White Sand Beaches Of The Maldives",
        "Engraving",
        "Environmental Art",
        "Escher's Staircase Illusion",
        "Escher",
        "Etching Press",
        "Eternal Sunshine Of The Spotless Mind's Lacuna",
        "Excitebike Tracks",
        "Fabric Scraps",
        "Fernando Botero",
        "Fifth Element's Fhloston Paradise",
        "Final Fantasy Cloud Of Darkness",
        "Fluxus",
        "Food Items",
        "Forbidden Grove",
        "Found Object Art",
        "Frank Stella",
        "Fresco Painting",
        "Fresco Secco Painting",
        "Fresco-Secco",
        "Fresco",
        "Frida Kahlo",
        "Galaga Bosses",
        "Gaudi's Sagrada Familia",
        "Geometric Abstraction",
        "Georgia O'keeffe",
        "Geothermal Geysers In Iceland",
        "Gerhard Richter",
        "Gesso",
        "Glade",
        "Glassblowing",
        "Glitter",
        "Glowing Jellyfish Bloom In The Deep Ocean",
        "Glowing Mushroom Forest At Night",
        "Glowing Mushrooms In A Forest",
        "Gouache Paint",
        "Gouache",
        "Gradius Backgrounds",
        "Graffiti",
        "Graffito",
        "Grand Bazaar",
        "Grand Budapest Hotel's Funicular Railway",
        "Grand Budapest Hotel",
        "Grand Prismatic Spring Aerial View",
        "Grand Prismatic Spring",
        "Graphite",
        "Green Hill Zone",
        "Gum Arabic",
        "Gustav Klimt",
        "Gyotaku",
        "H.R. Giger",
        "Hanging Gardens Of Babylon",
        "Henri Matisse",
        "Hidden Forest",
        "Hieronymus Bosch",
        "Historical Artifacts",
        "Hobbit Holes Of The Shire",
        "Hokusai",
        "Holographic Film",
        "Hyperrealism",
        "Hyrule Field",
        "Hyrule Overworld",
        "Ice Casting",
        "Ice Climbers Mountain",
        "Icelandic Geysers Erupting",
        "Icelandic Glaciers",
        "Icelandic Moss Fields",
        "Icy Landscape",
        "Impressionism",
        "Improvisation With Audience",
        "Improvisation",
        "Inception's Dream City",
        "Industrial Materials",
        "Ink Wash Painting",
        "Ink",
        "Inkjet Printing",
        "Inkwell Isles",
        "Installation Art",
        "Installations Using Everyday Objects",
        "Interactive Installation",
        "Interior Of A Gothic Cathedral",
        "Interior Of A Spaceship",
        "Isle Of The Dead",
        "Jackson Pollock",
        "James Turrell",
        "Japanese Bamboo Forest",
        "Jean Dubuffet",
        "Jean-Michel Basquiat",
        "Jeff Koons",
        "Jenny Holzer",
        "Joan Miró",
        "Jordan",
        "Judy Chicago",
        "Kamino",
        "Kara Walker",
        "Käthe Kollwitz",
        "Katsushika Hokusai",
        "Kehinde Wiley",
        "Keith Haring",
        "Kelp Forest",
        "Kill Bill's Tokyo Alleyway",
        "Kinbaku",
        "Kinetic Art",
        "Kinetic Sand",
        "Kinetic Sculpture",
        "Labyrinthine Corridors, Jellyfish Enemies",
        "Land Art",
        "Lavender Fields After Rain",
        "Lavender Fields At Sunrise",
        "Lavender Fields During A Thunderstorm",
        "Leather",
        "Leonardo Da Vinci",
        "Leonora Carrington",
        "Light And Shadow Installation",
        "Light Graffiti",
        "Light Installation",
        "Light Painting",
        "Light Sculpture",
        "Light",
        "Lighting Design",
        "Link's Awakening Koholint Island",
        "Louise Bourgeois",
        "Louise Nevelson",
        "Lush Amazon Rainforest Canopy",
        "Lush Rice Terraces With Farmers Working",
        "M.C. Escher's Lithograph 'Hand With Reflecting Sphere'",
        "Macrame",
        "Mad Max: Fury Road's Wasteland",
        "Magritte's 'The Son Of Man' Painting",
        "Man-Made Objects",
        "Manufactured Objects",
        "Marina Abramović",
        "Mark Rothko",
        "Mark Ryden",
        "Martian Canyons",
        "Martian Landscape",
        "Mary Cassatt",
        "Masai Mara During Migration",
        "Matrix",
        "Maurizio Cattelan",
        "Maw",
        "Medical Ephemera",
        "Mega Man Stages",
        "Mega Man Wily's Castle",
        "Metal Chasing",
        "Metal Scraps",
        "Metro",
        "Metroid Brinstar Caves",
        "Mezzotint",
        "Milky Way Galaxy",
        "Minimalism",
        "Mixed Media",
        "Miyazaki's Spirited Away Bathhouse",
        "Mojave Wasteland",
        "Monet's Haystack Series",
        "Monet's Water Lilies Close-Up",
        "Monet's Water Lily Pond",
        "Moon",
        "Mosaic",
        "Mushroom Kingdom",
        "Nam June Paik",
        "Natural Materials",
        "Natural Objects",
        "Natural Phenomena",
        "Natural Pigments",
        "Neo-Dada",
        "Neo-Expressionism",
        "Neon Dubai Cityscape",
        "Neon Las Vegas During The Day",
        "Neon Las Vegas From Space",
        "Neon Las Vegas Strip",
        "Neon Light Sculpture",
        "Neon Signs Of Hong Kong At Night",
        "Neon Tokyo Alleyway",
        "Neon Tokyo At Night From A Bullet Train Window",
        "Neon Tokyo During A Power Outage",
        "Neon Tokyo Streetscape",
        "Neon Tokyo Viewed From A Rooftop",
        "Neon-Lit Cityscape Reflected In A Rainy Street",
        "Neon",
        "Nibel",
        "Night City",
        "Ninja Gaiden Rooftops",
        "Objects",
        "Olafur Eliasson",
        "Op Art",
        "Organic Tunnels, Morphing Enemies",
        "Pablo Picasso",
        "Pac-Man Maze",
        "Pan's Labyrinth's Labyrinth",
        "Pandora",
        "Pastel Pencils",
        "Pencil",
        "Performance Art",
        "Petra,",
        "Photomontage",
        "Photorealism",
        "Pixel Art",
        "Plaster Casting",
        "Plaster",
        "Plastic Objects",
        "Pointillism",
        "Primitivism",
        "Punch-Out!! Ring",
        "Punch-Out!! Victory Fanfare",
        "Pyrography",
        "Quilling",
        "Quilting Fabric",
        "Quilting",
        "R-Type Force Fields",
        "Rainbow Road",
        "Rapture Central Bathysphere",
        "Rapture",
        "Religious Iconography",
        "Remedios Varo",
        "René Magritte",
        "Repoussé",
        "Resin Casting",
        "Reverse Glass Painting",
        "Rice Paddies During Harvest",
        "Rice Paper",
        "Rice",
        "Roy Lichtenstein",
        "Royal Tenenbaums' House",
        "Ruins",
        "Salt Dough",
        "Salt Flats At Sunset",
        "Salvador Dalí's Melting Clocks",
        "Salvador Dalí",
        "Sand Art",
        "Sand",
        "Sandblasting",
        "Scottish Highlands",
        "Scratchboard Art",
        "Scratchboard",
        "Script Adaptation",
        "Script",
        "Sculpting With Natural Ice",
        "Sea Glass",
        "Set Design",
        "Shibori",
        "Shining's Overlook Hotel",
        "Shipwreck Encrusted With Barnacles",
        "Shipwreck",
        "Shire",
        "Shirin Neshat",
        "Shivering Isles",
        "Side-Scrolling Streets",
        "Silent Hill",
        "Silicone",
        "Skyforge",
        "Skyloft",
        "Soft Pastels",
        "Sound Design",
        "Sound Installation",
        "Spirited Away's Bathhouse",
        "Spray Paint",
        "Stained Glass",
        "Stainless Steel",
        "Starry Sky Over The Atacama Desert",
        "Stencil Art",
        "Street Art Materials",
        "Street Art",
        "String Art",
        "Sumi-E",
        "Surrealism",
        "Surrealist Automatism",
        "Tachisme",
        "Takashi Murakami",
        "Tapestry Weaving",
        "Tapestry",
        "Technological Objects",
        "Tempera Painting",
        "Tetris Playing Field",
        "Textiles",
        "The Great Barrier Reef Aerial View",
        "The Great Salt Lake",
        "The Milky Way Galaxy Core",
        "Thread",
        "Tibetan Prayer Flags Fluttering In The Wind",
        "Tilt-Shift Photography",
        "Troll Markets Of Scandinavian Folklore",
        "Trompe-L'œil",
        "Tulip Fields",
        "Uldum",
        "Underdark",
        "Upside Down",
        "Van Gogh's Starry Night Sky",
        "Van Gogh's Wheat Field Under A Crows' Sky",
        "Vegetable Dyes",
        "Venetian Canals At Dusk",
        "Video Art",
        "Vincent Van Gogh",
        "Vines And Spores",
        "Volcanic Eruption",
        "Wakanda",
        "Warp Pipes",
        "Warp",
        "Wassily Kandinsky",
        "Watercolor Pencils",
        "Watercolor Sticks",
        "Watercolors",
        "Whiterun",
        "Wire Sculpture",
        "Woodcut Printing",
        "Woodcut",
        "Written Documents",
        "Yarn",
        "Yayoi Kusama",
        "Yinka Shonibare",
        "Yoko Ono",
        "Yves Klein",
        "Yves Tanguy",
        "Zdzisław Beksiński",
    };
    public static readonly string[] Sound =
    {
        "Aaron Copland",
        "Accordion",
        "Acid House",
        "Afro-Cuban Jazz",
        "Afrobeat",
        "Alice Coltrane",
        "Alphorn",
        "Animal Call",
        "Anklung",
        "Antonio Carlos Jobim",
        "Antonio Vivaldi",
        "Appalachian Folk",
        "Apples Crunching",
        "Aram Khachaturian",
        "Aretha Franklin",
        "Arvo Pärt",
        "Astor Piazzolla",
        "Autoharp",
        "Avant-Garde Jazz",
        "Bagpipes",
        "Balafon",
        "Balalaika",
        "Balinese Gamelan",
        "Balkan Brass",
        "Ball Bouncing",
        "Banjo",
        "Bansuri",
        "Barbershop Harmony",
        "Barbershop Quartet",
        "Baroque Fugue",
        "Béla Bartók",
        "Berimbau",
        "Bhangra",
        "Billie Holiday",
        "Birdsong",
        "Blacksmith Hammering Metal",
        "Blades Of A Helicopter Whirring",
        "Bluegrass",
        "Bob Dylan",
        "Bodhrán",
        "Bollywood Music",
        "Bollywood",
        "Book Slamming Shut",
        "Bossa Nova",
        "Bouzouki",
        "Brazilian Samba",
        "Brian Eno",
        "Butoh Music",
        "Cajon",
        "Cajón",
        "Cajun Music",
        "Cajun Zydeco",
        "Camera Shutter Click",
        "Camera Shutter Rapidly Clicking",
        "Carlos Santana",
        "Carnatic Music",
        "Castanets",
        "Cat Purring",
        "Cello",
        "Celtic Punk",
        "Chains Clanking",
        "Chainsaw Revving",
        "Chalk Screech On Blackboard",
        "Chapman Stick",
        "Chimes",
        "Chiptune",
        "City Ambience",
        "Clara Schumann",
        "Clarinet",
        "Claude Debussy",
        "Claves",
        "Clavichord",
        "Clavinet",
        "Clock Ticking",
        "Coffee Machine Brewing",
        "Coins Cascading",
        "Coins Clinking",
        "Coins Dropping",
        "Coins Rolling",
        "Crackling Fire",
        "Crackling Vinyl",
        "Crickets Chirping",
        "Crowd Cheering",
        "Crumhorn",
        "Cutting Fabric",
        "Daf",
        "Dan Moi",
        "Delta Blues",
        "Dhol",
        "Didgeridoo",
        "Digeridoo",
        "Dizi",
        "Djembe",
        "Dmitri Shostakovich",
        "Dog Barking",
        "Door Creaking",
        "Doorbell Chime",
        "Drone Music",
        "Drone",
        "Drum And Bass",
        "Drum Machine",
        "Drum Set",
        "Duke Ellington",
        "Edvard Grieg",
        "Electric Guitar",
        "Electroswing",
        "Ennio Morricone",
        "Erhu",
        "Eric Whitacre",
        "Erik Satie",
        "Factory Machinery",
        "Fireworks Exploding",
        "Flamenco",
        "Flute",
        "Footsteps On Creaky Stairs",
        "Footsteps On Gravel",
        "Fork Scraping Plate",
        "Franz Liszt",
        "Franz Schubert",
        "Gagaku",
        "Gagok",
        "Gamelan",
        "Giacomo Puccini",
        "Giuseppe Verdi",
        "Glass Clinking",
        "Glockenspiel",
        "Glowing Embers Crackling",
        "Gong Resonance",
        "Gong",
        "Gospel",
        "Gregorian Chant",
        "Guitar",
        "Gurgling Water",
        "Gustav Mahler",
        "Guzheng",
        "Gypsy Jazz",
        "Hammered Dulcimer",
        "Handpan",
        "Hang Drum",
        "Harmonica",
        "Harmonium",
        "Harp",
        "Harpsichord",
        "Heartbeat",
        "Hector Berlioz",
        "Henryk Górecki",
        "Hildegard Von Bingen",
        "Hindustani Classical",
        "Hot Air Balloon Burner Roaring",
        "Huqin",
        "Hurdy-Gurdy",
        "Igor Stravinsky",
        "Industrial",
        "Insects Buzzing",
        "J-Pop",
        "Jarocho",
        "Javanese Gamelan",
        "Jaw Harp",
        "Jean Sibelius",
        "Jig",
        "Jive",
        "Johann Sebastian Bach",
        "Johann Strauss Ii",
        "John Cage",
        "John Coltrane",
        "John Philip Sousa",
        "John Williams",
        "K-Pop",
        "Kalimba",
        "Kazoo",
        "Keyboard Clicks",
        "Keyboard",
        "Klezmer",
        "Koto",
        "Laughter Box",
        "Laughter",
        "Ludwig Van Beethoven",
        "Lute",
        "Marimba",
        "Mbira Music",
        "Mbira",
        "Melodica",
        "Meredith Monk",
        "Mongolian Throat Singing",
        "Morin Khuur",
        "Music Box",
        "Music Stand",
        "Neoclassical",
        "Norteño",
        "Oboe",
        "Ocarina",
        "Ocean Waves",
        "Olivier Messiaen",
        "Ondes Martenot",
        "Oud",
        "Pages Flipping Rapidly In A Book",
        "Pages Fluttering",
        "Pages Turning",
        "Pen Scratching Rapidly On Paper",
        "Pen Scratching",
        "Pencil Tapping",
        "Philip Glass",
        "Piano",
        "Pipa",
        "Popcorn Kernels Popping",
        "Post-Rock",
        "Progressive Metal",
        "Pyotr Ilyich Tchaikovsky",
        "Raï",
        "Rain Hammering On A Metal Roof",
        "Rain Splattering On Leaves",
        "Raindrops On Leaves",
        "Recorder",
        "Reggae Dub",
        "Reggaeton",
        "Rice Crackling",
        "Richard Wagner",
        "Rocks Tumbling Down A Mountainside",
        "Rustling Leaves",
        "Rusty Lock Creaking Open",
        "Rusty Swing Creaking Back And Forth",
        "Sanshin",
        "Santoor",
        "Sawing Wood",
        "Saxophone",
        "Scott Joplin",
        "Scuba Diver Breathing",
        "Sequencer",
        "Sergei Prokofiev",
        "Sergei Rachmaninoff",
        "Shakuhachi",
        "Shamisen",
        "Shanty",
        "Shepard's Flute",
        "Shoegaze",
        "Short Circuit Crackle",
        "Singing Bowl",
        "Sitar Music",
        "Sitar",
        "Sizzling Bacon",
        "Ska",
        "Slavic Polyphony",
        "Soldering Iron Hiss",
        "Sousaphone",
        "Sputtering Campfire Embers",
        "Sputtering Engine",
        "Steel Pan",
        "Steel Tongue Drum",
        "Steve Reich",
        "Sun Ra",
        "Synthwave",
        "Tabla",
        "Taiko Drum",
        "Taishogoto",
        "Tambourine",
        "Tambura",
        "Teletype Machine Clattering",
        "Theremin",
        "Thunderclap",
        "Toru Takemitsu",
        "Train Wheels Screeching",
        "Train Whistle",
        "Triangle",
        "Trumpet",
        "Tuvan Khoomei",
        "Tuvan Throat Singing",
        "Typing On A Typewriter",
        "Ukulele",
        "Vibraphone",
        "Violin",
        "Water Dripping",
        "Whales Singing",
        "Whistleblower",
        "Wind Chimes",
        "Wind Howling",
        "Wind Rushing Through A Tunnel",
        "Wind Whistling Through A Crack In The Wall",
        "Wind Whistling Through A Keyhole",
        "Wind Whistling Through Trees",
        "Wolfgang Amadeus Mozart",
        "Xylophone",
        "Zydeco",
    };
    public static readonly string[] Red =
        {
            "Abominable",
            "Abysmal",
            "Abyss",
            "Altar",
            "Amber",
            "Amour",
            "Antichrist",
            "Apricot",
            "Ardent",
            "Ardor",
            "Aurora",
            "Autumn",
            "Ballet",
            "Baphomet",
            "Beelzebub",
            "Bittersweet",
            "Black Magic",
            "Black Mass",
            "Blasphemous",
            "Blaze",
            "Blithe",
            "Bloodcurdling",
            "Bloodshed",
            "Bloodthirsty",
            "Blossom",
            "Blush",
            "Boudoir",
            "Brimstone",
            "Bubble",
            "Bubblegum",
            "Burgundy",
            "Caramel",
            "Cardinal",
            "Carmine",
            "Carnal",
            "Catacomb",
            "Cerise",
            "Cherries",
            "Cherub",
            "Chthonic",
            "Cinnabar",
            "Citrine",
            "Citrus",
            "Claret",
            "Cochineal",
            "Copper",
            "Coquelicot",
            "Coral",
            "Coruscate",
            "Cotton Candy",
            "Cotton",
            "Coven",
            "Crimson",
            "Crypt",
            "Cryptic",
            "Cthulhu",
            "Cupcake",
            "Cupid",
            "Curse",
            "Cursed",
            "Daemon",
            "Damnation",
            "Danger",
            "Dark Arts",
            "Deathly",
            "Delicate",
            "Demonology",
            "Deviltry",
            "Diabolical",
            "Dreadful",
            "Dystopian",
            "Eldritch",
            "Ember",
            "Embers",
            "Empyrean",
            "Enchantment",
            "Enigma",
            "Enticement",
            "Envy",
            "Ephemeral",
            "Eros",
            "Ethereal",
            "Euphoria",
            "Execrable",
            "Fiendish",
            "Fiery",
            "Fiesta",
            "Firelight",
            "Flamboyant",
            "Flamenco",
            "Flamingo",
            "Flare",
            "Fluff",
            "Forsaken",
            "Fuchsia",
            "Garnet",
            "Ghastly",
            "Ghoulish",
            "Glow",
            "Goldfish",
            "Gory",
            "Grace",
            "Grim Reaper",
            "Grim",
            "Grimdark",
            "Grotesque",
            "Hades",
            "Harvest",
            "Heartache",
            "Hellfire",
            "Hellhound",
            "Hellish",
            "Hex",
            "Hexcraft",
            "Incandescent",
            "Incendiary",
            "Infernal",
            "Infernalism",
            "Inferno",
            "Innocence",
            "Juicy",
            "Lollipop",
            "Luciferian",
            "Lurid",
            "Lust",
            "Luxuriant",
            "Macabre",
            "Magenta",
            "Magma",
            "Maleficent",
            "Malevolence",
            "Malevolent",
            "Malignant",
            "Maracas",
            "Maraschino",
            "Marigold",
            "Maroon",
            "Marshmallow",
            "Masquerade",
            "Melancholy",
            "Melody",
            "Merlot",
            "Morbid",
            "Nebula",
            "Necromancy",
            "Netherworld",
            "Nocturnal",
            "Obscure",
            "Occult",
            "Omen",
            "Opal",
            "Pagan",
            "Pandemonium",
            "Papaya",
            "Paprika",
            "Paradise",
            "Passion",
            "Peony",
            "Persimmon",
            "Pestilence",
            "Petal",
            "Phantom",
            "Phoenix",
            "Plague",
            "Pomegranate",
            "Possessed",
            "Possession",
            "Profane",
            "Pulsar",
            "Pumpkin",
            "Quasar",
            "Quiver",
            "Radiance",
            "Rebellion",
            "Reverie",
            "Revolution",
            "Rhapsody",
            "Ritual",
            "Ritualistic",
            "Rosé",
            "Rosewater",
            "Rouge",
            "Rubicund",
            "Ruby",
            "Rust",
            "Sacrilege",
            "Saffron",
            "Sakura",
            "Sangria",
            "Sanguinity",
            "Satanism",
            "Scarlet",
            "Seashell",
            "Sepulchral",
            "Serenade",
            "Serenity",
            "Shadowy",
            "Shamanic",
            "Shroud",
            "Sinister",
            "Sizzle",
            "Sorcerer",
            "Sorcery",
            "Sovereignty",
            "Specter",
            "Spectral",
            "Spice",
            "Strawberry",
            "Sublime",
            "Sunrise",
            "Sunset",
            "Surreptitious",
            "Sweetheart",
            "Tang",
            "Tangelo",
            "Tangerine",
            "Tangy",
            "Temerity",
            "Tempest",
            "Temptation",
            "Temptress",
            "Tenderness",
            "Terracotta",
            "Tiger",
            "Tomb",
            "Torturous",
            "Tryst",
            "Underworld",
            "Unforgiving",
            "Unholy",
            "Unredeemable",
            "Vermilion",
            "Vermillion",
            "Vibrant",
            "Vile",
            "Vitality",
            "Vivacious",
            "Voodoo Doll",
            "Voodoo",
            "Warlock",
            "Whimsical",
            "Whimsy",
            "Whisper",
            "Wicked",
            "Witchcraft",
            "Wraith",
            "Zest",
            "Zesty",
        };
    public static readonly string[] Yellow =
    {
        "Acceleration",
        "Acrimony",
        "Alchemy",
        "Alertness",
        "Algorithm",
        "Amber",
        "Amplifier",
        "Ancient Chinese Palace",
        "Ancient Egyptian Tomb",
        "Antique Book Binding",
        "Antique Map",
        "Antiquity",
        "Apathy",
        "Apricot",
        "Artificial Intelligence",
        "Audacity",
        "Augmented Reality",
        "Automation",
        "Autumn Leaves",
        "Bakelite",
        "Banana Laffy Taffy",
        "Banana Peel",
        "Banana Plantation",
        "Bark",
        "Beehive",
        "Bewitchment",
        "Bifurcation",
        "Birch Bark Canoe",
        "Blockchain",
        "Bolt",
        "Bronze",
        "Bumblebee",
        "Buttercup Meadow",
        "Buttercup",
        "Buttercups",
        "Butterflies",
        "Buzz",
        "Calmness",
        "Canary Islands",
        "Canary",
        "Capacitor",
        "Caution Tape",
        "Caution",
        "Celebration",
        "Champagne",
        "Charm",
        "Chartreuse",
        "Cheese Market",
        "Cheese",
        "Chessboard",
        "Chestnut",
        "Chicks",
        "Childhood Innocence",
        "Childhood",
        "Chocolate Chip Cookie",
        "Cinnamon",
        "Circuit",
        "Citrine",
        "Citrus",
        "Cocoa",
        "Coffee Grounds",
        "Coil",
        "Conductor",
        "Conjuration",
        "Construction Crane",
        "Construction Zone",
        "Contentment",
        "Convolution",
        "Corkscrew",
        "Corn On The Cob",
        "Cowardice",
        "Crackle",
        "Cream Cheese",
        "Cream",
        "Creativity",
        "Curiosity",
        "Currency",
        "Current",
        "Cybernetics",
        "Daffodil",
        "Daffodils",
        "Dandelion",
        "Dart",
        "Dawn",
        "Decadence",
        "Deception",
        "Departure",
        "Desert Landscape",
        "Diode",
        "Disdain",
        "Disintegration",
        "Disorientation",
        "Disquiet",
        "Dissonance",
        "Divination",
        "Drone",
        "Electrode",
        "Electromagnetism",
        "Ember",
        "Enchantment",
        "Envy",
        "Espresso Machine",
        "Espresso",
        "Euphoria",
        "Excitement",
        "Exploration",
        "Fakeness",
        "Fertile",
        "Fever",
        "Flamenco Dancer's Dress",
        "Flare",
        "Flash",
        "Flashbang",
        "Fleetness",
        "Flick",
        "Flicker",
        "Fortitude",
        "Fragile",
        "Fragility",
        "Freckles",
        "Furtive",
        "Generator",
        "Gilt",
        "Glide",
        "Glimmer",
        "Glint",
        "Glitter",
        "Gold Medal",
        "Gold Mine",
        "Gold",
        "Goldfish Cracker",
        "Goldfish",
        "Goldilocks",
        "Gyre",
        "Haste",
        "Helix",
        "Hex",
        "Highlighter",
        "Honey Gold",
        "Honey",
        "Honeycomb",
        "Humility",
        "Hurdle",
        "Ideas",
        "Illumination",
        "Immaturity",
        "Impermanence",
        "Incandescence",
        "Incantation",
        "Induction",
        "Innovation",
        "Intellectual Stimulation",
        "Internet Of Things",
        "Ivory",
        "Jacket",
        "Jealousy",
        "Joy",
        "Khaki",
        "Kindergarten Classroom",
        "Laughter",
        "Laurel",
        "Leather",
        "Lemon Chiffon",
        "Lemon Orchard",
        "Lemon",
        "Lemons",
        "Levity",
        "Lightheartedness",
        "Lightning",
        "Loneliness",
        "Luminescence",
        "Luxury",
        "Machine Learning",
        "Mahogany",
        "Maize",
        "Marigold",
        "Maturity",
        "Mellowness",
        "Mental Clarity",
        "Microchip",
        "Midas Touch",
        "Mimosa",
        "Mole",
        "Momentum",
        "Moonlight",
        "Mustard Factory",
        "Mustard",
        "Nanotechnology",
        "Necromancy",
        "Neon Sign District",
        "New Beginnings",
        "Nickel",
        "Nostalgia",
        "Ochre",
        "Olympic Podium",
        "Optimism",
        "Opulence",
        "Oscillator",
        "Pages",
        "Path",
        "Peace",
        "Pencils",
        "Perch",
        "Persistence",
        "Pineapple",
        "Playfulness",
        "Post-It Note",
        "Potion",
        "Power Grid",
        "Quantum Computing",
        "Race",
        "Radiance",
        "Rapid",
        "Rebellion",
        "Renewal",
        "Resistor",
        "Revelation",
        "Robotics",
        "Royalty",
        "Rubber Band",
        "Rubber Ducky",
        "Rune",
        "Rust",
        "Saddle",
        "Saffron",
        "Scaffolding",
        "School Bus",
        "School Cafeteria",
        "Sepia",
        "Serenity",
        "Shimmer",
        "Sigil",
        "Smart Technology",
        "Soar",
        "Software",
        "Soil",
        "Sorcery",
        "Spark",
        "Sparkle",
        "Sparkler",
        "Spell",
        "Spiral Galaxy",
        "Spiral Notebook",
        "Spiral Staircase",
        "Spire",
        "Sprint",
        "Stagnation",
        "Static Shock",
        "Static",
        "Strobe",
        "Summersaults",
        "Summertime",
        "Sunflower Field",
        "Sunflower Seed",
        "Sunflowers",
        "Swiftness",
        "Swirl",
        "Taxi Light",
        "Taxi Stand",
        "Taxi",
        "Tennis Court",
        "Terracotta",
        "Tesla Coil",
        "Thaumaturgy",
        "Thunderclap",
        "Topaz",
        "Tornado",
        "Tour De France",
        "Transformer",
        "Transience",
        "Treachery",
        "Treasure",
        "Trophy",
        "Truffle",
        "Twig",
        "Twist",
        "Twister",
        "Vanilla",
        "Velocity",
        "Vineyards",
        "Virtual Reality",
        "Voltage",
        "Vortex",
        "Vulnerability",
        "Walnut",
        "Warmth",
        "Warning",
        "Wearable Tech",
        "Whirlpool",
        "Whisper",
        "Whiz",
        "Wilderness",
        "Wizard",
        "Wizardry",
        "Yolk",
        "Zeus",
        "Zinc",
        "Zip",
        "Zoom",
    };
    public static readonly string[] Green =
    {
        "Absinthe",
        "Abundance",
        "Adventure",
        "Alien",
        "Ambivalence",
        "Apathy",
        "Apple",
        "Archipelago",
        "Artichoke",
        "Asparagus",
        "Avalanche",
        "Awning",
        "Backstage",
        "Balance",
        "Bamboo",
        "Bay",
        "Bayou",
        "Bean",
        "Bear",
        "Beret",
        "Billiard Ball",
        "Blizzard",
        "Bog",
        "Bowling Alley",
        "Broccoli Floret",
        "Butte",
        "Button",
        "Cactus Flower",
        "Cactus Garden",
        "Cactus",
        "Canopy",
        "Canyon",
        "Card",
        "Caterpillar",
        "Caution",
        "Cave",
        "Cavern",
        "Chartreuse",
        "Chessboard",
        "Chile Cheeseburger Stand",
        "Chili Pepper",
        "Chlorophyll",
        "Christmas Tree",
        "Circuit Board",
        "Cliffs",
        "Cliffside",
        "Clover",
        "Complacency",
        "Coral Reef",
        "Creek",
        "Cyclone",
        "Decay",
        "Deception",
        "Delta",
        "Desert",
        "Disgust",
        "Disquiet",
        "Dollar Bill",
        "Dragonfly Wings",
        "Drought",
        "Earthquake",
        "Earthslide",
        "Eco-Friendliness",
        "Ecto-1",
        "Elephant",
        "Elk",
        "Emerald Cut",
        "Emerald Mine",
        "Emerald Tablet",
        "Emerald",
        "Environmentalism",
        "Envy Adams' Emerald City",
        "Envy",
        "Eruption",
        "Estuary",
        "Eucalyptus",
        "Evergreen",
        "Fern",
        "Fingerprint",
        "Firework Burst",
        "Fixation",
        "Fjord",
        "Flood",
        "Flora",
        "Folklore",
        "Foothills",
        "Forbidden Knowledge",
        "Forest",
        "Fortune",
        "Fresh Starts",
        "Frog",
        "Gangrene",
        "Gecko",
        "Gemstone Cluster",
        "Genetically Modified Food Aisle",
        "Geyser",
        "Glacier",
        "Go-Ahead",
        "Gorge",
        "Granite",
        "Granny Smith Apple",
        "Grasshopper",
        "Grassland",
        "Greenback",
        "Greenhorn",
        "Growth Mindset",
        "Growth",
        "Guacamole",
        "Hope",
        "Hurricane",
        "Hyacinth",
        "Inexperience",
        "Insecurity",
        "Ivy",
        "Jade Market",
        "Jade",
        "Jaguar",
        "Jealousy",
        "Jungle",
        "Kermit Green",
        "Kermit The Frog",
        "Kermit",
        "Keyhole",
        "Khaki",
        "Kiwi Fruit",
        "Kiwi",
        "Kryptonite",
        "Ladybug",
        "Lagoon",
        "Lake",
        "Lakebed",
        "Landslide",
        "Leaf",
        "Leopard",
        "Lily Pad",
        "Lime",
        "Lion",
        "Lizard",
        "Luck",
        "Malachite",
        "Mango",
        "Mangrove",
        "Marble Quarry",
        "Marble",
        "Marsh",
        "Matcha",
        "Meadow",
        "Mesa",
        "Metamorphosis",
        "Miniature Golf Course",
        "Mint",
        "Monsoon",
        "Moss Patch",
        "Moss-Covered Ancient Ruins",
        "Moss",
        "Mountain",
        "Mudslide",
        "Naiveté",
        "National Identity",
        "Nausea",
        "Nickelodeon Studios",
        "Northern Lights",
        "Nostalgia",
        "Oasis",
        "Obsession",
        "Ocean",
        "Olive Drab",
        "Olive Oil",
        "Olive",
        "Onion",
        "Operating Room",
        "Opulence",
        "Orchid",
        "Paddy Field",
        "Palm",
        "Peace",
        "Peak",
        "Peninsula",
        "Peridot",
        "Permission",
        "Pickle",
        "Pine Tree",
        "Pine",
        "Pistachio",
        "Plateau",
        "Playing Card",
        "Playing Die",
        "Poison",
        "Pond",
        "Pool Table",
        "Possessiveness",
        "Power Button",
        "Prairie",
        "Praying Mantis",
        "Predator",
        "Rainforest Canopy",
        "Rainforest",
        "Rapids",
        "Ravine",
        "Recycling Center",
        "Redwood",
        "Refreshment",
        "Regeneration",
        "Relief",
        "Renewal",
        "Reptile",
        "Ridge",
        "River",
        "Riverbank",
        "Room",
        "Sandstorm",
        "Savanna",
        "Scottish Highlands",
        "Scottish Tartan",
        "Seafoam",
        "Second Chances",
        "Security",
        "Seiche",
        "Shamrock Shake Stand",
        "Shamrock",
        "Shrub",
        "Sinkhole",
        "Slime Splat",
        "Snake",
        "Stagnation",
        "Stream",
        "Streambed",
        "Summit",
        "Sustainability",
        "Swamp",
        "Tadpole",
        "Tea Bag",
        "Tea Plantation",
        "Tea",
        "Technological Innovation",
        "Tetris Z Block",
        "Thorn",
        "Thumb",
        "Thunderstorm",
        "Tiger",
        "Tornado",
        "Toxicity",
        "Traffic Light",
        "Tranquility",
        "Transformation",
        "Trust",
        "Tsunami",
        "Tundra",
        "Typhoon",
        "Unexplored Territory",
        "Vale",
        "Verdant",
        "Verdigris-Coated Copper Roof",
        "Verdigris",
        "Verdure",
        "Vine",
        "Vineyard",
        "Viridescent",
        "Volcano",
        "Waterfall",
        "Wealth",
        "Wetlands",
        "Wilderness",
        "Wildfire",
    };
    public static readonly string[] White =
    {
        "Achromatopsia",
        "Alba",
        "Albino Animal",
        "Albino",
        "Allegory",
        "Angel Falls",
        "Angel Halo",
        "Angelic",
        "Anticipation",
        "Apochromatism",
        "Apotheosis",
        "Archetype",
        "Ascendancy",
        "Ascension",
        "Aseptic Operating Room",
        "Assumption",
        "Asteroid",
        "Awareness",
        "Awe",
        "Baihu",
        "Beach",
        "Being",
        "Beingness",
        "Belyni",
        "Besmirched",
        "Black Hole",
        "Blancmange Mold",
        "Blank Page",
        "Blasphemous",
        "Blessed",
        "Blindness",
        "Blizzard",
        "Blood Cell",
        "Bone",
        "Boredom",
        "Buffalo Calf Woman",
        "Canvas",
        "Cave Formation",
        "Celestial",
        "Chalk Cliffs",
        "Chalk Mine",
        "Chalk",
        "Chastity",
        "Check",
        "Chocolate Chip",
        "Clarity",
        "Cleanliness",
        "Cloud Forest",
        "Cloud",
        "Cold",
        "Coldness",
        "Comet",
        "Condition",
        "Confusion",
        "Consciousness",
        "Constellation",
        "Contaminated",
        "Corrupted",
        "Cosmos",
        "Crescent Moon",
        "Cursed",
        "Damned",
        "Defiled",
        "Deity",
        "Demonic",
        "Desecrate",
        "Desert",
        "Diabolic",
        "Diamond",
        "Divine",
        "Dome",
        "Dove",
        "Dwarf",
        "Elephant",
        "Elevation",
        "Emptiness",
        "Enlightenment",
        "Epic",
        "Essence",
        "Eternal",
        "Exaltation",
        "Existence",
        "Fable",
        "Fairy Tale",
        "Flag",
        "Folklore",
        "Fragile",
        "Fragility",
        "Galaxy",
        "Ghost",
        "Glacier Surface",
        "Glare",
        "Glorification",
        "Godhead",
        "Gold",
        "Grotto",
        "Guan Yin",
        "Hateful",
        "Hathor",
        "Heavenly",
        "Heretical",
        "Hippolyta",
        "Hole Accretion Disk",
        "Hole",
        "Holy",
        "Hope",
        "Hotel",
        "House Lawn",
        "House",
        "Ice Rink",
        "Identity",
        "Impure",
        "Inanna",
        "Infernal",
        "Innocence",
        "Isle Of Skye",
        "Isolation",
        "Ix Chel",
        "Kayaking",
        "Knight",
        "Legend",
        "Leukothea",
        "Lie",
        "Lifeforce",
        "Light Bulb",
        "Loneliness",
        "Lore",
        "Mami Wata",
        "Marble Quarry",
        "Marker",
        "Marred",
        "Melancholy",
        "Menes",
        "Meteor",
        "Milk",
        "Minimalism",
        "Mourning",
        "Myth",
        "Mythology",
        "Mythos",
        "Nebula",
        "New Beginning",
        "New Beginnings",
        "Nirvana",
        "Noise Generator",
        "Noise Graph",
        "Noise Machine",
        "Noise Sleep App",
        "Noise Waveform",
        "Noise",
        "Numbness",
        "Omniscient",
        "Oshun",
        "Pagoda",
        "Parable",
        "Pass",
        "Peace",
        "Pele",
        "Pepper",
        "Placeholder",
        "Planet",
        "Pocket",
        "Polar Bear Habitat",
        "Polluted",
        "Porcelain Factory Workshop",
        "Porcelain Factory",
        "Porcelain",
        "Presence",
        "Profane",
        "Purity",
        "Quan Yin Pusa",
        "Quasar",
        "Rapids",
        "Rapture",
        "Reality",
        "Renewal",
        "Resurrection",
        "Rice Grain",
        "Rice Paddy Field",
        "Rice Paddy",
        "Room Art Installation",
        "Room",
        "Sachal Saraswati",
        "Sacred",
        "Saga",
        "Salt Flats",
        "Salvation",
        "Sanctified",
        "Sand Beach",
        "Sea",
        "Secrecy",
        "Selene",
        "Sentience",
        "Seraphic",
        "Serenity",
        "Silence",
        "Simplicity",
        "Sinful",
        "Skadi",
        "Ski Slope",
        "Ski Slopes",
        "Smirched",
        "Snowblindness",
        "Snowdrift",
        "Snowfall",
        "Snowflake",
        "Snowy Mountain Peak",
        "Soul",
        "Space",
        "Spoiled",
        "Stained",
        "Star",
        "Sterile",
        "Sterility",
        "Sublimation",
        "Subsistence",
        "Supernova",
        "Supreme",
        "Surprise",
        "Surrender",
        "Tabula Rasa",
        "Tainted",
        "Tank Mountain Regional Park",
        "Tara",
        "Tarnished",
        "Tennis Ball",
        "Tower Of Thessaloniki",
        "Tradition",
        "Transcendence",
        "Truffle",
        "Unclean",
        "Unhallowed",
        "Universe",
        "Uplift",
        "Ushas",
        "Vanilla",
        "Verse",
        "Vitality",
        "Vulnerability",
        "Water Rafting",
        "Wedding",
        "White-Out ",
        "Whiteboard",
        "Whitecaps",
        "Whitechapel District",
        "Whitewash",
        "Whitewater",
        "Wicked",
        "Winter Wonderland",
        "Xochipilli",
        "Yarn",
        "Yue Lao",
        "Yuki-Onna",
        "Zahao",
        "Zebra Stripes",
        "Zebra",
        "Zhi Nu",
        "Zorya Utrennyaya",
    };
}