name: bilirumine

volumes:
  comfy:
    external: true
  ollama:
    external: true

services:
  comfy:
    image: comfy
    build: 
      context: .
      dockerfile: ./comfy.Dockerfile
    ipc: host
    volumes:
      - ./input:/input
      - ~/Projects/ai/comfy/Comfy:/comfy
      - comfy:/root/.cache
    entrypoint: python /input/main.py
    devices:
      - /dev/video0:/dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all

  
  ollama:
    image: ollama
    build: 
      context: .
      dockerfile: ./ollama.Dockerfile
    volumes:
      - ollama:/root/.ollama