name: bilirumine

volumes:
  comfy:
    external: true
  audiocraft:
    external: true
  ollama:
    external: true

services:
  comfy:
    image: comfy
    build: ./Comfy
    ipc: host
    volumes:
      - ./input:/input
      - ~/Projects/ai/comfy/Comfy:/comfy
      - comfy:/root/.cache
    entrypoint: python /input/comfy.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
  
  audiocraft:
    image: audiocraft
    build: ./Audiocraft
    ipc: host
    volumes:
      - ./input:/input
      - ~/Projects/ai/audiocraft/audiocraft:/audiocraft
      - audiocraft:/root/.cache
    entrypoint: python /input/audiocraft.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all

  ollama:
    image: ollama
    build: 
      context: .
      dockerfile: ./Ollama
    ports:
      - 11432:11434
    volumes:
      - ollama:/root/.ollama