name: bilirumine

volumes:
  comfy:
    external: true
  ollama:
    external: true

services:
  comfy:
    image: comfy
    build: 
      context: .
      dockerfile: ./comfy.Dockerfile
    ipc: host
    volumes:
      - ./input:/input
      - ~/Projects/ai/comfy/Comfy:/comfy
      - comfy:/root/.cache
    entrypoint: python /input/main.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
  
  ollama:
    image: ollama
    build: 
      context: .
      dockerfile: ./ollama.Dockerfile
    ports:
      - 11432:11434
    volumes:
      - ./input:/input
      - ollama:/root/.ollama