name: bilirumine

volumes:
  comfy:
    external: true
  audiocraft:
    external: true
  ollama:
    external: true

services:
  comfy:
    image: comfy
    build: ./Comfy
    ipc: host
    volumes:
      - ./input:/input
      - ~/Projects/ai/comfy/Comfy:/comfy
      - comfy:/root/.cache
    entrypoint: python /input/image.py
    
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              device_ids: ['0']
  
  audiocraft:
    image: audiocraft
    build: ./Audiocraft
    ipc: host
    volumes:
      - ./input:/input
      - ~/Projects/ai/audiocraft/audiocraft:/audiocraft
      - audiocraft:/root/.cache
    entrypoint: python /input/sound.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              device_ids: ['1']

  ollama:
    image: ollama
    build: 
      context: .
      dockerfile: ./Ollama
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MAX_VRAM=2500000000
    ports:
      - 11432:11434
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              device_ids: ['1']