volumes:
  comfy:
    external: true

services:
  comfy:
    image: comfy
    ipc: host
    volumes:
      - ./input:/input
      - ~/Projects/ai/comfy/Comfy:/comfy
      - comfy:/root/.cache
    entrypoint: python /input/main.py
    devices:
      - /dev/video0:/dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all